# Generated by Django 4.1.7 on 2023-03-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restoran', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='photo',
            field=models.ImageField(upload_to='static/image'),
        ),
    ]
